version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./src/main/resources/photo:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
